name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

      - name: Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}
